export enum PayrollType { SALARY = 'SALARY', BONUS = 'BONUS', COMMISSION = 'COMMISSION', REGULAR = 'REGULAR' }
export enum AttendanceStatus { PRESENT = 'PRESENT', ABSENT = 'ABSENT', LATE = 'LATE', EXCUSED = 'EXCUSED' }
export enum PayrollStatus { DRAFT = 'DRAFT', PENDING = 'PENDING', APPROVED = 'APPROVED', PAID = 'PAID', CANCELLED = 'CANCELLED' }
export enum EmployeeStatus { ACTIVE = 'ACTIVE', INACTIVE = 'INACTIVE', ON_LEAVE = 'ON_LEAVE', TERMINATED = 'TERMINATED' }
export enum PayrollDetailType { EARNING = 'EARNING', DEDUCTION = 'DEDUCTION', TAX = 'TAX', REIMBURSEMENT = 'REIMBURSEMENT' }
export enum CustomerType { INDIVIDUAL = 'INDIVIDUAL', COMPANY = 'COMPANY', GOVERNMENT = 'GOVERNMENT' }
export enum ProjectStatus { PLANNED = 'PLANNED', IN_PROGRESS = 'IN_PROGRESS', COMPLETED = 'COMPLETED', ON_HOLD = 'ON_HOLD', CANCELLED = 'CANCELLED' }
export enum OpportunityStage { PROSPECTING = 'PROSPECTING', QUALIFICATION = 'QUALIFICATION', PROPOSAL = 'PROPOSAL', NEGOTIATION = 'NEGOTIATION', CLOSED_WON = 'CLOSED_WON', CLOSED_LOST = 'CLOSED_LOST' }
export enum AssetStatus { ACTIVE = 'ACTIVE', INACTIVE = 'INACTIVE', DISPOSED = 'DISPOSED', MAINTENANCE = 'MAINTENANCE' }
export enum DepreciationMethod { STRAIGHT_LINE = 'STRAIGHT_LINE', DECLINING_BALANCE = 'DECLINING_BALANCE', UNITS_OF_PRODUCTION = 'UNITS_OF_PRODUCTION' }
export enum TaskStatus { TODO = 'TODO', IN_PROGRESS = 'IN_PROGRESS', REVIEW = 'REVIEW', DONE = 'DONE' }
export enum CashFlowType { INFLOW = 'INFLOW', OUTFLOW = 'OUTFLOW' }
export enum BankAccountType { CHECKING = 'CHECKING', SAVINGS = 'SAVINGS', CREDIT = 'CREDIT' }
export enum ProductionOrderStatus { PLANNED = 'PLANNED', RELEASED = 'RELEASED', IN_PROGRESS = 'IN_PROGRESS', COMPLETED = 'COMPLETED', CANCELLED = 'CANCELLED' }
export enum BillOfMaterialsStatus { DRAFT = 'DRAFT', ACTIVE = 'ACTIVE', OBSOLETE = 'OBSOLETE' }
export * from './lib/dtos/payroll/calculate-payroll.dto';
