export enum CustomerType { INDIVIDUAL = 'INDIVIDUAL', COMPANY = 'COMPANY', GOVERNMENT = 'GOVERNMENT' }
export enum ProjectStatus { PLANNED = 'PLANNED', IN_PROGRESS = 'IN_PROGRESS', COMPLETED = 'COMPLETED', ON_HOLD = 'ON_HOLD', CANCELLED = 'CANCELLED' }
export enum OpportunityStage { PROSPECTING = 'PROSPECTING', QUALIFICATION = 'QUALIFICATION', PROPOSAL = 'PROPOSAL', NEGOTIATION = 'NEGOTIATION', CLOSED_WON = 'CLOSED_WON', CLOSED_LOST = 'CLOSED_LOST' }
export enum AssetStatus { ACTIVE = 'ACTIVE', INACTIVE = 'INACTIVE', DISPOSED = 'DISPOSED', MAINTENANCE = 'MAINTENANCE' }
export enum DepreciationMethod { STRAIGHT_LINE = 'STRAIGHT_LINE', DECLINING_BALANCE = 'DECLINING_BALANCE', UNITS_OF_PRODUCTION = 'UNITS_OF_PRODUCTION' }
export enum TaskStatus { TODO = 'TODO', IN_PROGRESS = 'IN_PROGRESS', REVIEW = 'REVIEW', DONE = 'DONE' }
export enum CashFlowType { INFLOW = 'INFLOW', OUTFLOW = 'OUTFLOW' }
export enum BankAccountType { CHECKING = 'CHECKING', SAVINGS = 'SAVINGS', CREDIT = 'CREDIT' }
export enum ProductionOrderStatus { PLANNED = 'PLANNED', RELEASED = 'RELEASED', IN_PROGRESS = 'IN_PROGRESS', COMPLETED = 'COMPLETED', CANCELLED = 'CANCELLED' }
export enum BillOfMaterialsStatus { DRAFT = 'DRAFT', ACTIVE = 'ACTIVE', OBSOLETE = 'OBSOLETE' }
